// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"day-26/database"
	"day-26/handler"
	"day-26/repository"
	"day-26/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializPaymentHandler() *handler.PaymentHandler {
	db := database.InitDB()
	paymentRepository := repository.NewPaymentRepository(db)
	paymentService := service.NewPaymentService(paymentRepository)
	paymentHandler := handler.NewPaymentHandler(paymentService)
	return paymentHandler
}

func InitializProcessHandler() *handler.OrderProcessHandler {
	db := database.InitDB()
	orderProcessRepository := repository.NewOrderProcessRepository(db)
	orderProcessService := service.NewOrderProcessService(orderProcessRepository)
	orderProcessHandler := handler.NewOrderProcessHandler(orderProcessService)
	return orderProcessHandler
}

func InitializDashboardHandler() *handler.DashboardHandler {
	db := database.InitDB()
	dashboardRepositoryDB := repository.NewDashboardRepository(db)
	dashboardService := service.NewDashboardService(dashboardRepositoryDB)
	dashboardHandler := handler.NewDashboardHandler(dashboardService)
	return dashboardHandler
}

func InitializAdminHandler() *handler.AdminHandler {
	db := database.InitDB()
	adminRepositoryDB := repository.NewAdminRepository(db)
	adminService := service.NewAdminService(adminRepositoryDB)
	adminHandler := handler.NewAdminHandler(adminService)
	return adminHandler
}

func InitializOrderHandler() *handler.OrderHandler {
	db := database.InitDB()
	orderRepositoryDB := repository.NewOrderRepository(db)
	orderService := service.NewOrderService(orderRepositoryDB)
	orderHandler := handler.NewOrderHandler(orderService)
	return orderHandler
}

func InitializBookHandler() *handler.BookHandler {
	db := database.InitDB()
	bookRepositoryDB := repository.NewBookRepository(db)
	bookService := service.NewBookService(bookRepositoryDB)
	bookHandler := handler.NewBookHandler(bookService)
	return bookHandler
}

// wire.go:

var paymentHandlerSet = wire.NewSet(database.InitDB, repository.NewPaymentRepository, service.NewPaymentService, handler.NewPaymentHandler)

var processHandlerSet = wire.NewSet(database.InitDB, repository.NewOrderProcessRepository, service.NewOrderProcessService, handler.NewOrderProcessHandler)

var dashboardHandlerSet = wire.NewSet(database.InitDB, repository.NewDashboardRepository, service.NewDashboardService, handler.NewDashboardHandler)

var adminHandlerSet = wire.NewSet(database.InitDB, repository.NewAdminRepository, service.NewAdminService, handler.NewAdminHandler)

var orderHandlerSet = wire.NewSet(database.InitDB, repository.NewOrderRepository, service.NewOrderService, handler.NewOrderHandler)

var bookHandlerSet = wire.NewSet(database.InitDB, repository.NewBookRepository, service.NewBookService, handler.NewBookHandler)
